language: java
jobs:
  include:
  - stage: deploy
    script: "./gradlew test"
before_install:
- openssl aes-256-cbc -K $encrypted_4bcfaff873d9_key -iv $encrypted_4bcfaff873d9_iv
  -in deploy_key.enc -out ./deploy_key -d

- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host ec2-18-222-202-175.us-east-2.compute.amazonaws.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key ubuntu@ec2-18-222-202-175.us-east-2.compute.amazonaws.com pwd
